### ISSUE TITLE
Reserved for future key characters

### ISSUE THREAD

**Issue by juliangut** [php-cache/issues#103]
I'm integrating doctrine adapter with [PHP-DI 6.x](https://github.com/PHP-DI/PHP-DI) and I've encountered that PHP-DI uses cache keys with back-slash, which upon this: https://github.com/php-cache/cache/blob/master/src/Adapter/Common/AbstractCachePool.php#L289 is not allowed in php-cache adapters (among other chars)

Could you explain why are this characters banned?

A solution like https://github.com/php-cache/doctrine-bridge/pull/10 could be included in the adapter as well

**Comment by prisis** [comment]
quote from psr-6 interface

Key - A string of at least one character that uniquely identifies a cached item. Implementing libraries MUST support keys consisting of the characters A-Z, a-z, 0-9, _, and . in any order in UTF-8 encoding and a length of up to 64 characters. Implementing libraries MAY support additional characters and encodings or longer lengths, but must support at least that minimum. Libraries are responsible for their own escaping of key strings as appropriate, but MUST be able to return the original unmodified key string. The following characters are reserved for future extensions and MUST NOT be supported by implementing libraries: {}()/\@:

**Comment by Nyholm** [comment]
It is a restriction from the PSR. The reson we do not "help" you and clean your keys is because it could have side effects. Example if we just removed the illegal char, the keys `foobar` and `foo\bar` would return the same item. 

We do clean it in the Doctrine bridge since it is a bridge, The user thinks they are using Doctrine. But that is a potential bug hiding... But there is no other way of doing a bridge. (What I know)

But if you use a PSR-6 cache you should know what characters you are using as keys.

**Comment by juliangut** [comment]
OK, I see it is in PSR16 as well, thanks
